# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 19:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_latitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('destination_longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('status', models.CharField(choices=[('RQ', 'Requested'), ('AC', 'Accepted'), ('EN', 'En Route'), ('IP', 'Ride In Progress'), ('CP', 'Ride Completed'), ('CN', 'Ride Canceled')], default='RQ', max_length=2)),
                ('driver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides_requested', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
